### ISSUE TITLE
Is there any reason why this template doesn't use tailwind-ppx?

### ISSUE THREAD

**Issue by JasoonS** [ryyppy/rescript-nextjs-template#33]
I'm curious if there are any blockers are deal-breakers against tailwind-ppx that make you hesitant to add it to this template?
https://github.com/dylanirlbeck/tailwind-ppx

**Comment by ryyppy** [comment]
We don't promote the usage of ppxes, because they make your projects very brittle for future compiler upgrades, and they are actually also not optimized for ReScript usage (they tend to make the build slower due to the way how ppxes are invoked).

For tailwind-ppx, I don't see any need, nor value, since editor tooling like VSCode's tailwind extension gives me enough support already (code completion, automatic classname ordering, etc.). Adding considerable compiling overhead just for finding typos is not worth it for a default template.

For those who still find it useful, they may add it themselves.

**Comment by JasoonS** [comment]
Makes sense, thanks! 

(I'll close this issue)
