### ISSUE TITLE
Temporarily target commonjs

### ISSUE THREAD

**Issue by ghost** [ryyppy/rescript-nextjs-template#53]
Until NextJS supports ES6, I think it would be less confusing for newcomers to this template to have the transpiling from es6 to commonjs happen before the rescript build happens, and have rescript target commonjs. I haven't tried this myself.

**Comment by ryyppy** [comment]
I care about upwards compatibility. Can you point out why it is confusing to newcomers? Any concrete roadblockers there?

**Comment by ghost** [comment]
There are recent questions in the forums where people seem unclear on when the modules are using es6 or commonjs. Also, I don't think that most people realize that the following is happening (which I may have wrong):

- various npm libraries come in commonjs format and are left as is
- some libraries come in esm format and are left as is initially, source files in this repo are generated in esm format, and then after rescript compilation, the libraries are converted to commonjs format by next-transpile-modules
- the output from the rescript compiler is converted to commonjs format by nextjs during the next build process
- node and the browser ultimately evaluate these commonjs format modules, and can choke if any raw sections of the rescript source files use esm syntax

**Comment by ryyppy** [comment]
> There are recent questions in the forums where people seem unclear on when the modules are using es6 or commonjs

I assume you are referring to [this thread](https://forum.rescript-lang.org/t/yarn-workspaces-example/1826/16) in particular? This issue is a culmination of many bad tools clashed together, and this problem would also happen on any other non-NextJS related setup.

I am especially confused about this, because ppl try to set up micro-modules in a "monorepo like setup" just so they can [reuse a single-file package with a 100 lines](https://github.com/bettercart/rescript-dinero/blob/master/src/Dinero.res). Just copy paste that thing and adapt it to your needs, instead of trying to make things work that are overly complex for no obvious benefit.

> some libraries come in esm format and are left as is initially, source files in this repo are generated in esm format, and then after rescript compilation, the libraries are converted to commonjs format by next-transpile-modules

Webpack compiles ES6 / commonjs to some webpack compatible intermediate format. I don't think it makes things easier / more idiomatic for Webpack to handle commonjs. The only complexity is `next-transpile-modules` to make sure that specific node_modules files get some extra pre-processing. The rest is a matter of setting your bsconfig.json to either es6, or commonjs.

> node and the browser ultimately evaluate these commonjs format modules, and can choke if any raw sections of the rescript source files use esm syntax

Yes, and node will also choke on any ES6 module that uses the `require` format, so in some situations your code will break if you are using modern libraries that rely on ES6 in a commonjs setup. It's a goose chase that will only be solved with extra plumbing on a case-by-case basis. 

Besides, NextJS is currently pursuing the ES6 module approach, as seen in their [Next 11 Preview Release](https://nextjs.org/blog/next-11#nextjs-live-preview-release) section.

In the end, if ppl desire to use `commonjs`, they can easily just switch the bsconfig.json output option to commonjs, and the suffix to `.bs.js` and it should just work?

**Comment by ryyppy** [comment]
Follow up: I added some extra instructions to the README on how to convert back to commonjs.

https://github.com/ryyppy/rescript-nextjs-template#es6-vs-commonjs

**Comment by ghost** [comment]
I think you have addressed this, so I will close now.

**Comment by ghost** [comment]
The instructions can tell the user to remove next-transpile-modules, since rescript libraries will be generated in commonjs format.

**Comment by ghost** [comment]
I suspect that you can remove next-transpile-modules from this template, now that NextJS has an experimental esm support feature.
